name: Build and Release Go Service

on:
    push:
        branches:
        - main # mainブランチへのプッシュでトリガー
jobs:
  build-windows-service:
    # セルフホストランナーを指定
    runs-on: [self-hosted,Windows,X64,test] # Windowsセルフホストランナーで実行

    permissions:
      contents: write # リリースアセットのアップロードのために必要

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # リポジトリのコードをチェックアウト

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # 使用するGoのバージョンを指定 (例: 1.22)

    - name: Set Adobe Reader Path Environment Variable
      run: |
        # 環境変数を設定 (ランナーマシン上の実際のパスに合わせる)
        # この環境変数は、Goプログラムの printPDF 関数で使用されます。
        echo "ADOBE_READER_PATH=C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe" >> $GITHUB_ENV
      shell: powershell # PowerShellシェルを使用

    - name: Build Go Service Executable
      run: |
        # Goサービス実行ファイルをビルド
        # -ldflags="-H windowsgui" でコンソールウィンドウを非表示にする
        # -o で出力ファイル名を指定
        go build -ldflags="-H windowsgui" -o MyGoHTTPServer.exe main.go
      shell: powershell # PowerShellシェルを使用

    - name: Compress Executable
      run: |
        # ビルドされた実行ファイルをZIPファイルに圧縮
        # 関連する設定ファイルなどもここに追加できます
        Compress-Archive -Path MyGoHTTPServer.exe -DestinationPath my-go-http-service-windows.zip
      shell: powershell # PowerShellシェルを使用

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1 # リリースを作成し、アセットをアップロードするアクション
    
      with:
        tag_name: ${{ github.ref_name }} # タグ名をリリース名として使用
        name: Release ${{ github.ref_name }} # リリース名
        body: Automated release from GitHub Actions. # リリース説明
        draft: false # ドラフトリリースではない
        prerelease: false # プレリリースではない
        files: |
          ./my-go-http-service-windows.zip # アップロードするZIPファイル

    # オプション: GitHub Actionsのアーティファクトとしてもアップロードしたい場合
    # - name: Upload Artifact (Optional)
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: my-go-http-service-windows-package
    #     path: my-go-http-service-windows.zip
    #     retention-days: 7